- build.gradle
- gradle.properties
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-plugin/build.gradle
- pom.xml
I also updated the third-party libraries to the level of 1.554.2.
With this update Jenkins kindly reminds you of [JENKINS-4409](https://issues.jenkins-ci.org/browse/JENKINS-4409) when your dev machine runs Windows. Temp files also leaked in previous releases, but now an exception is logged as well...
> Updated Jenkins core to 1.554.2 

- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/ExecuteDslScripts/config.jelly
Adapted from https://github.com/jenkinsci/groovy-plugin/blob/groovy-1.24/src/main/resources/hudson/plugins/groovy/StringScriptSource/config.jelly.
This PR introduces https://github.com/jenkinsci/jenkins/pull/1460 issue. Can be easily made bigger and happen only when the radio button is not preselected.
> [FIXED JENKINS-16355] Enable codemirror

- docs/Job-reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/DslContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Allow an additional classpath to be specified for the `dsl` step.
> Allow `additionalClasspath` to be specified for the `job-dsl-plugin`

- docs/Home.md
- docs/Job-DSL-Commands.md
- docs/Job-reference.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
Deprecated perModuleEmail and removed element from config XML template, see [JENKINS-26284](https://issues.jenkins-ci.org/browse/JENKINS-26284)
> deprecated perModuleEmail

- docs/Home.md
- docs/Job-reference.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/TimeoutContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
Timeout enum is used internally only and now deprecated. Removed the switch statement and the list of if statements by moving some logic to TimeoutContext. Deprecated the failBuild action with a boolean parameter, removed the abortBuild action with a boolean parameter.
> Build Timeout Refactoring

- docs/Home.md
- docs/Job-reference.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/AbstractJobManagement.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/AbstractJobManagementSpec.groovy
- job-dsl-core/src/test/resources/deprecation-subject.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java
Finding credentials by description has been deprecated. The argument passed to the `credentials` methods (e.g. for Git or Subversion SCM) has been used to find credentials by comparing the value to the credential's
description and ID. Using the description can cause problems because it's not enforced that descriptions are unique. But it was useful because the ID was a generated UUID that could not be changed and thus was neither portable between Jenkins instances nor readable in scripts as a symbolic name would be. Since version 1.21, the credentials plugin supports to set the ID to any unique value when creating new credentials. So it's no longer necessary to use the description for matching.
> Finding credentials by description is deprecated

- docs/Job-DSL-Commands.md
The value for type of a matrix job should be Matrix according to the source code.
> Wrong value for Matrix type

- docs/Home.md
- docs/Job-reference.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.java
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/LocalRepositoryLocation.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/common/MavenContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/MavenContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/MavenJob.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/MavenJobSpec.groovy
Deprecated and replaced the only context interface (MavenContext), a star import (LocalRepositoryLocation) and an enum with camel case values (LocalRepositoryLocation).
> Refactoring of MavenContext and LocalRepositoryLocation

- docs/View-Reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ListView.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
JENKINS-27495
Adds the recurse parameter, which is necessary when using the folders
plugin to get things to actually show up.
> JENKINS-27495 Add recurse parameter to listView

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotPropSeriesContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotSeriesContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Noticed this when you did the cleanup and removed the label option from XML series in the docs.
The label option is only for properties files so I've fixed the code to do so.
> Removing label option for non properties file types.

- docs/Home.md
- docs/Job-DSL-Commands.md
- docs/View-Reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobParent.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/ViewFactory.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/CategorizationCriteriaContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/CategorizedJobsView.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/GroupingRuleContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/NestedViewsContext.groovy
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/views/CategorizedJobsView-template.xml
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobParentSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/CategorizedJobsViewSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/NestedViewSpec.groovy
Closes [JENKINS-26423](https://issues.jenkins-ci.org/browse/JENKINS-26423)
```groovy
categorizedJobsView(String name) {  
// list view options
// ... (all of them)
// categorized jobs view options
categorizationCriteria {
groupingRule {
groupRegex(String groupRegex)
namingRule(String namingRule)
}
// short alias for groupingRule
byRegexWithNaming(String groupRegex, String namingRule)
}
}
```
Creates a new view that is very similar to the standard Jenkins List Views, but where you can group jobs and categorize them according to regular expressions. Requires the [Categorized Jobs View](https://wiki.jenkins-ci.org/display/JENKINS/Categorized+Jobs+View).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/job-dsl-p …
> [JENKINS-26423] Support Categorized Job View plugin

- config/codenarc/rules.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/AbstractJobManagement.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/FileJobManagement.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/MemoryJobManagement.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/MockJobManagement.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/AbstractJobManagementSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/MockJobManagementSpec.groovy
Added pre-set permissions to FileJobManagement and MemoryJobManagement to be able to use the permissions DSL outside of Jenkins. That's a follow-up of JENKINS-16365. Also did some refactoring to introduce a base class for all non-Jenkins JobManagement implementations.
> [JENKINS-16365] Added pre-set permissions

- Vagrantfile
I switched to Ubuntu because vagrant-vbguest has problems with CentOS (https://github.com/dotless-de/vagrant-vbguest/issues/141). I also added configuration for the vagrant-cachier plugin to speed up provisioning.
> use trusty64 box and add vagrant-cachier configuration

- Vagrantfile
- docs/Home.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/MockJobManagement.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/CoreVersionASTTransformationSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
- job-dsl-plugin/build.gradle
See [JENKINS-28167](https://issues.jenkins-ci.org/browse/JENKINS-28167) for details.
> [JENKINS-28167] updated minimum Jenkins core version to 1.565

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
This NPE would happen if the dsl created a folder as well as a corresponding view in that folder. When later both are deleted, updateGeneratedViews cannot find the parent, which result in an NPE in logging.
> NPE guard for views in folders that have already been deleted.

- docs/Home.md
- docs/Job-reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/HtmlReportTargetContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
I added the option to the DSL and added test cases for it.
Documentation is updated and Release Notes entry was added. 
What do you think?
> Jenkins 28564: Add new option "Always link to last build on job page" for html-publisher	

- docs/Home.md
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
The update is handled by Jenkins when creating, updating or deleting projects:
https://github.com/jenkinsci/jenkins/blob/jenkins-1.565/core/src/main/java/hudson/model/ItemGroupMixIn.java#L264
https://github.com/jenkinsci/jenkins/blob/jenkins-1.565/core/src/main/java/hudson/model/AbstractItem.java#L614
https://github.com/jenkinsci/jenkins/blob/jenkins-1.565/core/src/main/java/hudson/model/AbstractItem.java#L534
> removed unnecessary update of Jenkins project dependency graph

- docs/Home.md
- docs/Job-reference.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/ConditionalStepsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/MultiJobStepContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/MultiJobStepContextSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Replaces #513 and #516.
I removed the generics since those do not fix IDE support in this case. So there will be no IDE support for multi-job phases in conditional build steps, but that's a minor issue compare to having no support for conditional multi-job phases at all. It's also an issue for the new API browser (#479) because it uses the same annotations as the IDE support.
I also added deprecation warnings, release notes and updated the documentation.
@wolfs please review and if it's OK, hit the merge button and close #513 and #516.
> Restore Multijob phase support in conditionalSteps

- docs/Job-reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/BuildBlockerContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
- support for job blocking on global or node level
- support for job blocking based on status of queued jobs
(buildable only/all jobs in queue)
> Added support for new options introduced in build-blocker-plugin

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java
If ID and description are the same for a credential, a misleading deprecation warning was logged.
Changing the order of checks prevents the warning for this case.
> Fixed deprecation warning in getCredentialsId.

- docs/Folder-Reference.md
- docs/Home.md
- docs/Job-DSL-Commands.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Folder.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/FolderSpec.groovy
The Folders Plugin allows to set one of the views in the folder as the default initial view (called primaryView). Job-Dsl-Plugin hardcoded this to the "All" view. This `primaryView` option allows you to change it.
> [JENKINS-29498] added the primaryView option to Folders

- docs/Job-reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/MatrixJob.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/MatrixJobSpec.groovy
Matrix job does not have a convinience method to add
childCustomWorkspace. Define it.
--Define childCustomWorkspace method in MatrixJob
--Add a unit test for it
--Update job reference
[JENKINS-29375]
> method to add childCustomWorkspace to MatrixJob

- build.gradle
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.java
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobParent.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/common/PublishOverSshServerContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/DslScriptLoaderSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/WithXmlActionSpec.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ScriptRequestGenerator.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedJobsAction.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedJobsBuildAction.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsAction.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsBuildAction.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedViewsAction.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedViewsBuildAction.java
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
job-dsl-plugin uses transitive dependency from Jenkins core.
This should avoid problem if Jenkins core uses a different of Guava than the Job DSL plugin.
> removed dependency on Guava from job-dsl-core module

- docs/Job-reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ArchiveXUnitContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
1.95 and above supports gtester/glib2
https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin
> [JENKINS-29753] Add support for gtester of xUnit plugin

- docs/Job-reference.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/parameter/ActiveChoiceContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/parameter/ActiveChoiceReferenceContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
Support for additional type of Active Choice Parameter - Active Choice Reference Parameter. Added tests, documentation and one new class `ActiveChoiceReferenceContext` extending `ActiveChoiceContext`. As `activeChoiceReferenceParam` differs from `activeChoiceParam` in reference part and XML element name, XML part is moved to parametrized `createGenericActiveChoiceNode`.
> Support for Active Choice Reference Parameter

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
`<parameters class="linked-hash-map"/>` is required in active choice
parameters definition for proper function of reactive variants.
Without this parameters node generated by job-dsl, reference
variants do not work properly and you need to open job configuration
and save it.
> Adding parameters node for active choice parameters

- job-dsl-plugin/build.gradle
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ConfigFileProviderHelper.groovy
More recent version (starting with 2.8.1) have a different constructor signature for `MavenSettingsConfig` causing the DSL plugin to fail with later version of the plugin (was failing yesterday with 2.9.2).
Switched to using a data binder similar to StaplerRequest.bind to support any constructor signature as long as it is annotated with `@DataBoundConstructor`. Constructor parameters are now provided as a Map and all supported parameters will be passed to the constructor.
> [JENKINS-30013] Add support for later versions of config-file-provider-plugin

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
`job-dsl` should gracefully continue when a template no longer exists.
For background, this is what happened, we had a build which threw an exception unexpectedly:
```
07:02:52 ERROR: Build step failed with exception
07:02:52 java.util.ConcurrentModificationException
07:02:52 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
07:02:52 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
07:02:52 	at com.google.common.collect.AbstractMultimap$WrappedCollection$WrappedIterator.next(AbstractMultimap.java:531)
07:02:52 	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:648)
07:02:52 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
07:02:52 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:13 …
```
> Fix NPE When GeneratedJobs is out of Date.

- job-dsl-api-viewer/src/css/main.less
- job-dsl-api-viewer/src/js/app.js
- job-dsl-api-viewer/src/templates/detail.hbs
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/doc/ApiDocGenerator.groovy
This PR adds the initial implementation of the auto-generating documentation. 
demo: http://sheehan.github.io/job-dsl-plugin/
Steps for publishing the docs:
1. Run ```./gradlew generateApiDoc``` 
* This will create a JSON file in `/job-dsl-plugin-viewer/data/dsl-<version>.json`
2. Add the version to the select at `/job-dsl-api-viewer/index.html` if not already there
3. Run `./gradlew :job-dsl-api-viewer:publishGhPages`
The generator will use JavaDoc for the method documentation. For longer docs, you can create a markdown file in `job-dsl-core/api-docs/` instead. I've moved a few docs there from the wiki so far.
> dsl api documentation

- docs/Home.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
The plugin is no longer available in the Update Center, see https://github.com/jenkinsci/backend-update-center2/commit/79ca047996ccdb360c864c3866ed25445fbe05b6.
> deprecated support for the JSHint Checkstyle Plugin

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/extendedEmail.groovy
In the API viewer for extendedEmail it lists a configure step that sets
contentType to ‘html’.  This causes emails to fail with an error about
“expected / found ;”.    If I manually select the HTML content type
with the email-ext plugin, it puts
<contentType>text/html</contentType>.  This change prepends “text/“
> contentType error in API Viewer for email-ext

- README.md
- docs/Job-DSL-Commands.md
Updates several examples. Also removed any prominent references to job templating as it's not the best practice.
> [JENKINS-30433] Updated README

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/phabricatorNotifier.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext/phabricator.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PhabricatorNotifierContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/PhabricatorContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
I'm trying to add the support for the Phabricator-Jenkins plugin, however I'm not really sure why the build fails:
```
javaposse.jobdsl.dsl.DslScriptLoaderSpec > use @Grab FAILED
org.codehaus.groovy.control.MultipleCompilationErrorsException at DslScriptLoaderSpec.groovy:183
```
My first guess is that it's due to the plugin not being officially hosted yet, as the registration is in progress (see https://github.com/uber/phabricator-jenkins-plugin/issues/8).
Thoughts?
> Add support for Phabricator Plugin

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/pullRequest.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/GitHubPullRequestBuilderCommitStatusContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/GitHubPullRequestBuilderExtensionContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
This is needed right now because a change in the ghprb will not print the default status URL if no statusUrl node is present in the config.
> Add statusUrl support in the pull request builder

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/common/WorkspaceCleanupContext.groovy
Prefer `protected` so that Categories will work properly with `PreBuildCleanupContext`.
This issue can be reproduced by this simple job script which will throw an exception. The script does not throw an exeption when not using Categories:
```groovy
class Bar { }
use (Bar) {
freeStyleJob('deb-promote') {
wrappers {
preBuildCleanup {
excludePattern 'deb/'
}
}
}
}
```
Exception:
```
Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.wrapper.PreBuildCleanupContext.addPattern() is applicable for argument types: (java.lang.String, java.lang.String) values: [EXCLUDE, deb/
```
For reference, see https://issues.apache.org/jira/browse/GROOVY-6263
> Fix use of Categories with WorkspaceCleanupContext

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy
I attempted to improve the documentation for using multi-line cron/scm entries. My initial intuition for this was to use multiple cron()'s, but only one showed up. I'm happy to adjust this language as desired and add it other places so others can discover this; I don't think it should require specific language/parsing knowledge to know how to separate lines. Or, perhaps the solution is that multiple cron()s and scm()s should be allowed. Just throwing one documentation solution out there :)
> document multi-line triggers

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/JacocoContext.groovy
Seems to be a typo -- there is no 10.0.13, only 1.0.13: https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin
> Use correct JaCoCo plugin versioning

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.java
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java
* unwrap InvocationTargetExceptions when calling extensions to hide the fact that extensions are called through reflection
* log stack traces for all exceptions but DslScriptExceptions so that users can debug their scripts without looking in Jenkins logs
* only wrap GroovyRuntimeException in DslScriptException so that users can debug their scripts without looking in Jenkins logs but problems like simple syntax errors do not cause stack traces
> [JENKINS-31174] Improved logging

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext/buildFailureAnalyzer.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext/scannerJobProperty.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/properties/PropertiesContextSpec.groovy
Added [Build Failure Analyzer](https://wiki.jenkins-ci.org/display/JENKINS/Build+Failure+Analyzer) plugin support
- https://issues.jenkins-ci.org/browse/JENKINS-31544
> [JENKINS-31544] Added Build failure analyzer plugin support

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/vSphereDeployFromTemplate.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31818
Although there are 3 different non mandatory fields:
- linkedClone(false)
- resourcePool('')
- datastore('')
How do I manage those attribute? Should I create a DSL Context for Vsphere? If so, does it make one per build step?
Any suggestions?
Cheers
> [JENKINS-31818] Added support for vSphereDeployFromTemplate step

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
The Jenkins plugin annotates the Targets text box as follows:
"Whitespace separated list of accounts to send notifications to
(like 'peter@myjabberserver.org') -- for group chats, prepend a '*'
(e.g.  '*commitroom@conference.myjabberserver.org') -- note that
JIDs that contain '@conference.' are automatically recognized as
group chats (no need to prepend '*')"
This patch makes `publishJabber` behave as documented above.
> Make publishJabber treat target as group if it contains "@conference."

- build.gradle
- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/deployToWeblogic.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.java
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/WeblogicDeployerContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/WeblogicDeployerPolicyContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/WeblogicDeployerTaskContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
New rebased/updated version of PR https://github.com/jenkinsci/job-dsl-plugin/pull/158 and https://github.com/jenkinsci/job-dsl-plugin/pull/608:
This pull request adds support for the weblogic-deployer-plugin:
```groovy
job('example') {
publishers {
deployToWeblogic {
mustExitOnFailure(true)
forceStopOnFirstFailure(true)
// at least one task is required
task {
// required
weblogicEnvironmentTargetedName('dev_environment')
// required
deploymentName('myApplicationName')
deploymentTargets('AdminServer')
// required
builtResourceRegexToDeploy('myApp\\.ear')
// required
baseResourcesGeneratedDirectory('')
// required
taskName('Deploy myApp to DEV Server')
jdkName('JDK_7')
jdkHome('C:\\Program Files\\Java\\jdk1.7.0_65')
stageMode(WeblogicDeploymentStageModes.STAGE)
commandLine('-debug -remote …
```
> [Jenkins 21880] weblogic deployer plugin support

- docs/Home.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/MavenWrapperContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/MavenWrapperContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-32135
Plugin url is not part of the docs: https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.wrapper.MavenWrapperContext.mavenRelease
> [JENKINS-32135] Fixed documentation for the M2 Release Plugin

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/jobs/BuildFlowJob/buildNeedsWorkspace.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/BuildFlowJob.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/BuildFlowJobSpec.groovy
Honors existing Jenkins behavior of not adding this option, thereby keeping it false, by default.
use `buildNeedsWorkspace()` to set to true for a build flow job
> Adds support for buildNeedsWorkspace option in Build Flow Plugin

- docs/Home.md
- docs/Migration.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/postBuildScripts.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PostBuildScriptsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
In addtion to that, it forces a minimum version since latest release was early 2015 and previous one was in 2013, so I believe we can force people to use the latest one instead.
> [FIXED JENKINS-31853] Added scriptOnlyIfFailure and markBuildUnstable options

- docs/Home.md
- docs/Job-DSL-Commands.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/DslFactory/workflowMultiBranchJob.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/OrphanedItemStrategyContext/orphanedItemStrategy.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/WorkflowMultiBranchSourcesContext/branchSource.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslFactory.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobParent.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BranchSourceContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/OrphanedItemStrategyContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/WorkflowMultiBranchSourcesContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/WorkflowMultiBranchJob.groovy
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/WorkflowMultiBranchJob-template.xml
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobParentSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/WorkflowMultiBranchJobSpec.groovy
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-31671
Jenkins Workflow Plugin 1.11: 
* https://github.com/jenkinsci/workflow-plugin/blob/master/CHANGES.md
* https://www.cloudbees.com/blog/workflow-19-and-multibranch-beta
> [JENKINS-31671] Add support for workflow multibranch

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/ReleaseContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
Hi,
This is a pull request for [JENKINS-32285](https://issues.jenkins-ci.org/browse/JENKINS-32285), allowing the possibility for other plugins to contribute to the `parameters` section, by making the `BuildParametersContext` extensible.
Best regards,
Damien.
> JENKINS-32285 Making BuildParametersContext extensible

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/systemGroovyScriptFile.groovy
`systemGroovyScriptFile.groovy` example file instead used `systemGroovyCommand`.
> Fixing typo in systemGroovyScriptFile example

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/StaticAnalysisPublisherContextSpec.groovy
"healthy" and "unHealthy" default to empty strings as values in the GUI and null gets written to xml as a string "null", which leads to errors in runtime.
> Fix for unspecified health in Warnings plugin

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
Passed build.
Ran embedded server and installed JaCoCo 2.0.1 plugin to verify the following Job DSL -
```
listView("TestView") {
columns {
status()
weather()
name()
lastSuccess()
lastFailure()
lastDuration()
jacoco()
}
jobs {
}
}
```
Generated a List View that I could then add the above job to and see that the view included the column and the View XML was correct -
```
<?xml version="1.0" encoding="UTF-8"?>
<hudson.model.ListView>
<name>TestView</name>
<filterExecutors>false</filterExecutors>
<filterQueue>false</filterQueue>
<properties class="hudson.model.View$PropertyList"/>
<jobNames>
<comparator class="hudson.util.CaseInsensitiveComparator"/>
<string>TestDSL</string>
</jobNames>
<jobFilters/>
<columns>
<hudson.views.StatusColumn/>
<hudson.views.WeatherColumn/> …
```
> Add DSL support for JaCoCo Line Coverage column via 'jacoco' method

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/rundeck.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/RundeckContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
As shouldIncludeRundeckLogs requires shouldFailTheBuild to be set I also added a shortcut `shouldWaitForRundeckJobAndIncludeRundeckLogs`. It is convenient, but I don't know how it fits into job-dsl conventions.
> [Rundeck] Support for shouldIncludeRundeckLogs

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/ScmContext/perforcep4.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/ScmContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/P4Context.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
This is a basic implementation of support for Perforce Software's "p4 plugin". This uses credentials instead of username and password which are used by the older "perforce plugin".
Compared the to syntax I suggested in JENKINS-32391 I decided to call the DSL command "perforcep4" rather than "perforce". This leaves the possibility of renaming the older "p4" support to "perforce" and this to p4 if that is desired (so that the commands match the plugin names).
Also I decided to implement the "Manual" workspace within a context instead of as one method. This leaves room for further "workspace behaviours" to be implemented ("Spec File", "Static", "Streams", "Template").
> [JENKINS-32391] Basic implementation of Perforce P4 plugin support.

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/BuildParametersContext/nonStoredPasswordParam.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/BuildParametersContext/nonStoredPasswordParameter.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
Added the nonStoredPassword parameter included with the mask-passwords plugin. This allows a job to take in a password as user input. The password is not persisted between builds and there is no default so password security shouldn't be a concern.
> Add non stored password parameter

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitContext.groovy
The Git plugin offers two clean checkboxes, one for before and one for after. This option enables the "clean after" behavior, so let's sync the documentation to not be confusing / misleading. Other references appear to be correct.
> correctly document GitContext's clean

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/IrcContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/JabberContext.groovy
instant-messaging-plugin supports NEW_FAILURE_AND_FIXED since 2013,
so enabling usage of it in DSL for Jabber and IRC plugins.
> Support NEW_FAILURE_AND_FIXED instant messaging strategy

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ArchiveXUnitThresholdContext.groovy
Fixes a simple typo I noticed while browsing the docs.  'skiped' -> 'skipped'
> Fix typo 'skiped'

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/NodeEnhancement.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/NodeEnhancementSpec.groovy
Recent changes to NodeEnhancement are throwing an exception when encountering a Node with null attributes.
In my case, that was coming from here: https://github.com/jenkinsci/job-dsl-plugin/blob/fd173066cb95849c7b7402060131dba18a00150b/job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy#L247
> handle node with null attributes

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ArchiveXUnitThresholdContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
The default values for the thresholds are empty strings in the GUI and not zeros. Zeros have a different meaning, they enforce having 0 failed tests, while an empty string means "do not check this threshold".
> Allow thresholds to be empty

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/ScmContext/git.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/StrategyContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
See also [JENKINS-33782](https://issues.jenkins-ci.org/browse/JENKINS-33782).
> [FIXED JENKINS-33782] Add support for git-chooser-alternative to the scm helper's StrategyContext

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitExtensionContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitSubmoduleOptionsContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
- [JENKINS-33968](https://issues.jenkins-ci.org/browse/JENKINS-33968)
```groovy
job('example-1') {
scm {
git {
remote {
name('remoteB')
url('git@server:account/repo1.git')
}
extensions {
submoduleOptions {
reference('/foo/bar')
}
}
}
}
}
```
> [JENKINS-33968] Enhanced git with submodule reference repo

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/msbuild.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/MSBuildContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
- Added support for [MSBuild plugin](https://wiki.jenkins-ci.org/display/JENKINS/MSBuild+Plugin)
- [JENKINS-33825](https://issues.jenkins-ci.org/browse/JENKINS-33825)
- Already tested it out in an vanilla jenkins instance
> [JENKINS-33825] Added support for MSBuild Plugin

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitExtensionContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitSubmoduleOptionsContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
- [JENKINS-33967](https://issues.jenkins-ci.org/browse/JENKINS-33967)
```groovy
job('example-1') {
scm {
git {
remote {
name('remoteB')
url('git@server:account/repo1.git')
}
extensions {
submoduleOptions {
timeout(40)
}
}
}
}
}
```
> [JENKINS-33967] Enhanced git with submodule timeout

- docs/Tutorial---Using-the-Jenkins-Job-DSL.md
Updated the git repo to pull from quidryan in the first tutorial which works for all of the demo projects for job-dsl-plugin and updated the Jenkins SCM triggers timer to H/15 from */15 to follow Jenkins best practices.
> Updated git repo for tutorial and triggers to new H/ format instead of */

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContext/github.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/GitHubBranchSourceContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContextsSpec.groovy
Adds support for the github-branch-source plugin to the Jenkins DSL for multibranch workflow (now called Pipeline) jobs (https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+GitHub+Branch+Source+Plugin)
> Add GitHub branch source support

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/DslFactory/dashboardView.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/DashboardView.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/portlets/BuildStatisticsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/portlets/DashboardPortletContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/portlets/IframeContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/portlets/JenkinsJobsListContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/portlets/TestTrendChartContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/DashboardViewSpec.groovy
Adds more options for dashboard view plugin.
> Add more options for dashboard view

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/extractJiraEnvironmentVariables.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
The JIRA plugin support was missing this feature implemented in version 2.2 of the plugin.
> Add support for extracting related JIRA environment variables

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/DslFactory/multibranchPipelineJob.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/DslFactory/pipelineJob.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslFactory.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobParent.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobParentSpec.groovy
I've noticed some confusion on the part of users when they don't see
"pipelineJob" available in Job DSL, just "workflowJob", since Workflow
got renamed to Pipeline and all. Adding these methods should help with
that. I didn't change everything referencing "workflowJob" in docs to
"pipelineJob", though. Not sure what the right approach there is.
cc @reviewbybees
> Adding pipelineJob/multibranchPipelineJob methods.

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/gitlabPush.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/GitLabTriggerContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
- `allowAllBraches` paramater was replaced by `branchFilterType`
- new parameter `targetBranchRegex`
- new property `gitlabConnection` which sets the gitlab connection a job
should use
> [JENKINS-34534] support for gitlab-plugin 1.2.0

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext/timeout.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/TimeoutContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
* Now it can use "String type" in absolute timeout. (fixed [JENKINS-35228](https://issues.jenkins-ci.org/browse/JENKINS-35228))
* Added 3 examples to API document.
* Update the release note
* Added a test case: Test absolute timeout configuration working using string type
> [FIXED JENKINS-35228] Not possible to use String in absolute timeout

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/GradleContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
Gradle Plugin up to version 1.24 passes job parameters as system properties (-D). The new Gradle Plugin 1.25 (yet to be released) will offer an option to pass job parameters as Gradle Properties (-P).
The new feature is version agnostic and will only kick in for versions >= 1.25. For compatibility reasons, the default is to use the old behaviour (system properties).
The PR for the Gradle Plugin feature itself is https://github.com/jenkinsci/gradle-plugin/pull/27
> [JENKINS-33093] Support new feature of upcoming Gradle Plugin 1.25

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/GroovyPostbuildContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Add possibility for user to define classpath for groovy post build plugin.
groovyPostBuild {
script('foo')
behavior(PublisherContext.Behavior.MarkFailed)
sandbox()
classpath(["foo","bar"])
}
> Add classpath attribute for groovy post build plugin

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslFactory.groovy
The overload for the pipelineJob method mentions a workflow job, but the new terminology (pipeline job) should be used.
> Fixed outdated documentation.

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/RundeckContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
With rundeck plugin version 3.5.4 (May 19, 2016), you have to select a
configured rundeck instance - or the job won't work.
Hint: No rundeck info for your job is displayed on the job page, when no
instance is selected!
> Add support to select a rundeck instance

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JobDslPlugin.groovy
Not all masters may actually have the default update center configured
- if they're only using custom update centers with ids other than
"default", the API viewer barfs. This change instead uses
Jenkins.instance.updateCenter.coreSource, which will get the first
update site that provides core updates. If you've got the default
update center configured, that'll be used. If there are no update
centers supplying core updates configured (which can happen in some
weird edge cases), then it'll still fail, but I think this is the
cleanest fix for most use cases.
cc @reviewbybees
> [FIXED JENKINS-37103] Use coreSource instead of default update center

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ScriptRequestGenerator.groovy
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ScriptRequestGeneratorSpec.groovy
Fixed problem with indentation in multi-line content when used in additionalClasspath variable. It happens when value contains tabs or spaces. This results in error:
```
...
Processing DSL script job.groovy
ERROR: startup failed:
workspace:/jobs/job.groovy: n: unable to resolve class ...
``` 
Sample XML file:
```xml
<project>
...
<builders>
<javaposse.jobdsl.plugin.ExecuteDslScripts plugin="job-dsl@1.50">
<targets>jobs/job.groovy</targets>
<usingScriptText>false</usingScriptText>
<ignoreExisting>false</ignoreExisting>
<ignoreMissingFiles>false</ignoreMissingFiles>
<removedJobAction>DELETE</removedJobAction>
<removedViewAction>DELETE</removedViewAction>
<lookupStrategy>JENKINS_ROOT</lookupStrategy>
<additionalClasspath>src/main/resources
src/main/groovy
lib/*.jar</additionalClasspath> …
```
> Fixed problem with indentation in multi-line content

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/CredentialsBindingContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy
Make CredentialsBindingContext extensible, in order to allow credentials binding for any type
of StandardCredentials for which a (Multi)Binding implementation is available.
For instance, I have a custom binding implementation for DockerServerCredentials (jenkinsci/docker-commons-plugin#54) and I would like to use it from job DSL scripts.
> Make CredentialsBindingContext extensible

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JobDslPlugin.groovy
When there is an update site which could not be fetched (invalid URL, offline Jenkins server, etc), then UpdateSite.JSONObject will be null, which triggers a NullPointerException in JobDslPlugin.generateUpdateCenter().
Requests to /plugin/job-dsl/api-viewer/build/data/update-center.jsonp fail, and the API Viewer breaks
because some code in Dsl.js expect that window.updateCenter.data is defined.
> Fix NPE in JobDslPlugin.generateUpdateCenter()

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitCloneOptionsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitExtensionContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
This helps fix issues with shallow clones on Gerrit repositories.
> Add Git CloneOption for honorRefspec

- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/archiveJunit.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ArchiveJUnitContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Hey guys, I came across this value while translating some build jobs into the job dsl. Would it be possible to get this added?
> Add support for `healthScaleFactor` in JUnit Plugin.

- docs/Home.md
- docs/Migration.md
- job-dsl-api-viewer/src/assets/javascripts/Dsl.js
- job-dsl-api-viewer/src/assets/javascripts/templates/context.hbs
- job-dsl-api-viewer/src/assets/javascripts/templates/detail.hbs
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/doc/ApiDocGenerator.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
The DSL support for the Rundeck plugin is a pain to test. It's not possible to configure the Rundeck notifier and save a job's config page without a running instance of Rundeck. I do not want to setup Rundeck for testing Job DSL. Because of that, built-in DSL support is deprecated and will eventually be removed. The [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL) is a suitable replacement.
> deprecated support for the Rundeck plugin

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitExtensionContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitSubmoduleOptionsContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
According to a feature in the git plugin, which was added since 3.0.0 version. See https://issues.jenkins-ci.org/browse/JENKINS-20941
> Added parentCredentials option to the git submodule options

- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/BuildFlowJob-template.xml
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/FreeStyleJob-template.xml
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/IvyJob-template.xml
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/MatrixJob-template.xml
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/MavenJob-template.xml
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/MultiJob-template.xml
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/DslSampleSpec.groovy
- job-dsl-core/src/test/resources/JENKINS_32941.xml
This has been obsolete since 1.527, specifically https://github.com/jenkinsci/jenkins/commit/47de54d070f67af95b4fefb6d006a72bb31a5cb8
> Remove 'class' attribute from <trigger/> elements

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PostBuildScriptsContext.groovy
I'm sorry to say, but I was unable to test it. Building the plugin with gradle fails both with, and without this change because of some missing class.
> add support for PostBuildScripts's executeOn setting

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/GerritContext.groovy
The keyword names in angle brackets in groovydoc were ommited when
rendering the documentation
> Fix documentation for gerrit

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
Jenkins::Tasks::BuildWrapperProxy is the correct class for 0.10 - 0.13 ruby-runtime
> Eliminate bad plugin version check

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/AbstractDslScriptLoader.groovy
not sure why it's suddenly broken, but it's probably a good idea to use only the file name instead of the path for the generated class name
> fixed ClassFormatError

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/HtmlReportTargetContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
New feature has been added in html publisher plugin that allows user to specify title for html files shown in the build [html publisher doc](https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin). A new property called reportTitles added in the html publisher plugin. In this pull request, new property is added to dsl plugin, so that users uses html publisher can make use of new feature
> Html publisher plugin report title on v1.13

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/GradleContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
Issue
-----
With gradle plugin version 1.26 the description field was removed.
This leads to exceptions like the following:
hudson.model.FreeStyleProject	SomeJob	MissingFieldException: No field 'description' found in class 'hudson.plugins.gradle.Gradle'
The faulty commit is
https://github.com/jenkinsci/gradle-plugin/commit/ffddd0b33e7c820b16d97b5e60a330fe81917556
Solution
--------
* The description field is only written when old (< 1.26) gradle versions are installed.
* The description field is marked deprecated.
[FIXES JENKINS-44217]
> JENKINS-44217 fixes incompatibility with the gradle plugin version 1.26

- docs/Home.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/DeployArtifactsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/MavenPublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/MavenPublisherContextSpec.groovy
Add support for the optional releaseEnvVar property in the maven plugin
RedeployPublisher.
This property controls if the publisher should be skipped when the
environment variable value is ‘true’.
> JENKINS-44357 - add releaseEnvVar property to DeployArtifactsContext

- docs/Home.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/SectionsContext/jobGraphs.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/SectionsContext/testResult.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/SectionsContext/text.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/SectionsContext/viewListing.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ListViewSectionContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/SectionContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/SectionsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/TextSectionContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ViewListingSectionContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/SectionedViewSpec.groovy
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-complexListViewSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-complexTextSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-complexViewListSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-defaults.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-minimalJobGraphsSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-minimalListViewSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-minimalTestResultSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-minimalTextSection.xml
- job-dsl-core/src/test/resources/javaposse/jobdsl/dsl/views/SectionedViewSpec-minimalViewListSection.xml
I want to create sectioned views with sections other than job lists. This branch adds the other sections of the view to the DSL.
I'm not a java/groovy dev, so I don't know if there's a better way of implementing the methods in SectionsContext.groovy. There's a lot of copy-paste in there.
Also, `./gradlew build` fails at least 95% of the time with an error
> :job-dsl-core:generateApiDocException in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiRenderWriter
but that's not related to the changes here.
> Sectioned view

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/PhaseJobContext.groovy
UNSTABLE option is not visible in documentation:
https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.step.PhaseJobContext.killPhaseCondition
> Fix braces in comment

- docs/User-Power-Moves.md
`@version@` will be replaced by the current version when the docs are published.
> simpler steps to run DSL scripts locally

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/NotificationEndpointContext.groovy
These are the two new supported events: (queued and failed) per below
https://github.com/jenkinsci/notification-plugin/blob/6773a44ff00d9f6d7e9df792920c40a2fb62e1aa/src/main/resources/com/tikal/hudson/plugins/notification/HudsonNotificationProperty/config.jelly#L37-L42
> add two new supported events by notifications plugin

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/MultiBranchProjectFactoryContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/OrganizationFolderJob.groovy
- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/jobs/OrganizationFolderJob-template.xml
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/OrganizationFolderJobSpec.groovy
issue: https://issues.jenkins-ci.org/browse/JENKINS-45528
- Disabled test because I don't know the right way to implement the clearing use case
> Add support to configure `projectFactories` for organization folders

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/GitPublisherContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/NoteToPushContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Added support for publishing git notes in the post-build gitpublisher.
This is more or less copy-paste from the implementation of the git tag
implementation.
> Add support for git notes in git publisher

- docs/Home.md
- docs/Real-World-Examples.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/AbstractDslScriptLoader.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/SandboxDslScriptLoader.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ScriptApprovalDslScriptLoader.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/SecureDslScriptLoader.groovy
- job-dsl-plugin/src/test/groovy/ScriptHelper.groovy
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
... when script security sandbox is enabled
The idea is to add an `URLClassLoader` as parent for the `SandboxResolvingClassLoader`. The `URLClassLoader` is created with a single URL, the directory of the DSL script to execute or the root of the workspace for inline scripts. And the `URLClassLoader` will not resolve compiles classes (`findClass` throws `ClassNotFoundException`), but allows to read resources when the `Item.WORKSPACE` has been granted. This allows the `GroovyClassLoader` from `GroovyShell` to pick up Groovy source files. And since the compiler configuration contains the `SandboxTransformer`, those source files are subject to the sandbox.
> allow import of Groovy code from the workspace 

- build.gradle
See https://github.com/jenkinsci/jenkins/pull/3120 for background. This plugin required a special whitelist entry in core for `javaposse.jobdsl.dsl.GeneratedJob`. Presumably the intent is that everything in the `job-dsl-core` JAR is treated as part of the plugin and will not be exposing anything dangerous for Java or XStream serialization.
@reviewbybees
> Jenkins-ClassFilter-Whitelisted: true

- docs/Home.md
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JobDslWhitelist.groovy
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
… when using script security sandbox.
The idea is to allow dynamic calls to instances of the three `Context` classes used to implement the Automatically Generated DSL (`AbstractExtensibleContext`, `DescribableContext`, `DescribableListContext`) when the receiver is part of the Job DSL plugin (it's classloader is the same as the classloader of `JobDslWhitelist`).
> [JENKINS-47560] fixed support for Automatically Generated DSL

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/CpsScmContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/WorkflowDefinitionContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/WorkflowJobSpec.groovy
Add the `lightweight` property to cpsScm, to allow lightweight checkout
to retrieve the pipeline script.
> Support lightweight checkout for pipeline jobs

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitCloneOptionsContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitExtensionContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
Add `depth` parameter in git cloneOptions context.
> Allow specify git clone depth

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/CpsScmContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/WorkflowJobSpec.groovy
Default Jenkinsfile name is `Jenkinsfile`, not `JenkinsFile`.
> Fix typo for default Jenkinsfile name

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
Given that the Active Choices plugin has been reintegrated in the Update Center after it broke its
required dependency to Scriptler and made it optional, would it be possible to un-deprecate it, or maybe
deprecate only the Scriptler integration in that plugin ?
> Undeprecate uno-choice support after security fixes

- docs/Testing-DSL-Scripts.md
[JENKINS-48877](https://issues.jenkins-ci.org/browse/JENKINS-48877)
Wiki update: 
- Bumped jenkins-test-harness and also removed the war-for-test classifier as required since version 2.64 onwards
Further details:
- https://groups.google.com/forum/#!topic/job-dsl-plugin/oPjqGR6VTpU
@reviewbybees
> [JENKINS-48877] war-for-test classifier is not supported from 2.64+

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java
- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/Messages.properties
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
As discussed on [#1108](https://github.com/jenkinsci/job-dsl-plugin/pull/1108) let's always delete and re-create views when type changes.
> Delete and re-create view if type changes

- docs/The-Configure-Block.md
Simple correction of a typo in The Configure Block wiki page.
> Typo correction in The Configure Block wiki

- build.gradle
Previously, both the maven and the maven-publish plugin were used.
However, only either one should be used. As the used configuration
syntax is the one of the maven-publish plugin, remove the maven plugin.
/cc @mnonnenmacher
> Gradle: Only use the maven-publish plugin

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildSelectorParameterContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/CopyArtifactSelectorContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
This is a PR to allow using the Build Selector Parameter for the Copy Artifact Plugin (https://wiki.jenkins.io/display/JENKINS/Copy+Artifact+Plugin),
NOTE: I do know that an auto-generated method for that in theory exists, however, it does not work properly. Using it according to the API causes the following error:
> ERROR: Found multiple extensions which provide method upstream with arguments [devskiller.services.ServicesJobBuilder$_configureDeployJob_closure4$_closure20$_closure25$_closure26$_closure27@12fb813d]: [[com.tikal.jenkins.plugins.multijob.MultiJobBuildSelector, hudson.plugins.copyartifact.TriggeredBuildSelector]]
> Finished: FAILURE
The changes in this PR have been tested and they generate the parameter correctly.
> Add build selector parameter

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslFactory.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/WorkflowDefinitionContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobParentSpec.groovy
Nothing should be referring to `workflow-aggregator`, which was just a do-nothing plugin created to make it easier for Jenkins 1.x users to install a bunch of Pipeline plugins. Be more specific about the plugins actually required for certain elements.
> Do not require workflow-aggregator

- job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/Folder-template.xml
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/FolderSpec.groovy
All view should have the (unlocalized) name "all". Otherwise, every start of Jenkins, all names are converted, taking a couple (15 in our case) minutes.
See: https://issues.jenkins-ci.org/browse/JENKINS-38606
> [JENKINS-56505] Fix for JENKINS-38606 related log spam

- .gitignore
- docs/JCasC-Job-DSL.md
- job-dsl-plugin/build.gradle
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/ConfigurableScriptSource.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/FromFileScriptSource.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/FromUrlScriptSource.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/InlineGroovyScriptSource.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/ScriptSource.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/SeedJobConfigurator.java
- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/casc/FromFileScriptSource/schema.jelly
- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/casc/FromUrlScriptSource/schema.jelly
- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/casc/InlineGroovyScriptSource/schema.jelly
- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/casc/SeedJobConfigurator/schema.jelly
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ConfigurationAsCodeTest.java
- job-dsl-plugin/src/test/resources/javaposse/jobdsl/plugin/ConfigurationAsCodeTest.yaml
- job-dsl-plugin/src/test/resources/javaposse/jobdsl/plugin/testjob.groovy
It is using a released version and the changes that have happened to the configurator in the meantime.
SeedJob configurator now has access to JCasC secrets.
> Support seed job creation in Configuration as Code, updated

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Previously, there was no invocation of the buildDescription step that
would set the description from a regex: the plugin would see the empty
string `description` and faithfully set that ignoring the other
configuration parameter.
> DescriptionSetter: Omit description when empty

- docs/Job-DSL-Commands.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslFactory.groovy
There still have been some traces of `workflowJob` and `multibranchWorkflowJob`.
> Fix documentation regarding old *workflow* job methods

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsAction.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsRunAction.java
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
This should fix JENKINS-44142 too.
Basically every job dsl build step creates a new build action with its generated items. Multiply build step creates the same amount of actions. But for comparing which items were generated during the build it use the first one which jenkins returns. So with settings RemovedJobAction.DELETE it always deletes actions which were not created by the particular step (even those which were created in the same build by previous job dsl build steps.
> JENKINS-29784: DSL Job View shows many copies of Generated Items

- docs/Testing-DSL-Scripts.md
This PR simplifies the `getJobFiles` method in the example test script using `groovy.util.FileNameFinder`.
This is my first Groovy-related PR - please be gentle!
> Testing-DSL-Scripts.md: Simplify `getJobFiles`

- docs/Home.md
- docs/Migration.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Project.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/WorkflowJob.groovy
The `concurrentBuild` field was deprecated and replaced by [`DisableConcurrentBuildsJobProperty`](https://github.com/jenkinsci/workflow-job-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProperty.java) in jenkinsci/workflow-job-plugin#8, which was released in Pipeline: Job 2.4. Use of this deprecated field exposes [JENKINS-53775](https://issues.jenkins-ci.org/browse/JENKINS-53775).
Encourage Job DSL users to move to the non-deprecated [`DisableConcurrentBuildsJobProperty`](https://github.com/jenkinsci/workflow-job-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProperty.java) (which avoids JENKINS-53775) by deprecating the `concurrentBuild` method in Pipeline jobs in Job DSL. …
> Deprecate support for concurrentBuild in Pipeline jobs

- docs/JCasC.md
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/casc/SeedJobConfigurator.java
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ConfigurationAsCodeTest.java
- job-dsl-plugin/src/test/resources/javaposse/jobdsl/plugin/ConfigurationAsCodeTest.yaml
An implementation of the improvement proposed in [JENKINS-59037](https://issues.jenkins-ci.org/browse/JENKINS-59037).
> [JENKINS-59037] Allow passing values from casc yaml to job dsl.

- Jenkinsfile
See https://issues.jenkins-ci.org/browse/INFRA-2243
This change moves the plugin from the deprecated functionality to the new Pipeline Library step. There should be no differences in the behavior.
> [INFRA-2243 ] - Switch CI to the new buildPluginWithGradle() step

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java
- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/Messages.properties
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
Fixes [JENKINS-59995](https://issues.jenkins-ci.org/browse/JENKINS-59995):
1) Processing DSL failed at creating top-level (not in folder) items, if the seed job itself was located inside a folder.
2) Two seed jobs could override each other's results when creating item inside folder
The error message format can be left the way it was, but the lack of additional info cost us quite a few attempts at understanding what was going on :)
> fix folder-related bugs in createOrUpdateConfig

- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/ExecuteDslScripts/help-removedJobAction.html
In the `removedJobAction` documentation, this should read 'lose', not 'loose'.
> Fix typo in `removedJobAction` documentation

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/SvnCheckoutStrategy.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
The subversion plugin has the option to leave the working copy untouched with the [NoopUpdater](https://github.com/jenkinsci/subversion-plugin/blob/master/src/main/java/hudson/scm/subversion/NoopUpdater.java).
These changes make this strategy also available for the DSL.
> Jenkins 58575 - Add Noop SVN Checkout Strategy

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/GeneratedJob.groovy
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-63056
Fixes an issue where removing the last folder of a specific casing will remove all jobs and history of that folder when the unreferenced action is marked to `DELETE`. This will actually just not add the item to the unreferenced list if it's still referenced under a different name.
Easiest way to reproduce this issue is to run the new test without the implementation, otherwise the information in the jira ticket above should have everything.
> JENKINS-63056: Fix casing issue with unreferenced items

- docs/Home.md
- job-dsl-plugin/build.gradle
- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
- job-dsl-plugin/src/test/resources/organizationfolder.xml
Similar to 8d8ea63fcefe0028c5168dffd9210955c41fe773, we should be able
to support organization folders not losing their credentials.
This requires we bump our dependency of `credentials` to pick up the
`branch-api` dependency.
We need to handle the various bits of metadata available in the
`OrganizationFolder`s, so our tests are slightly more complex than we
usually have.
Co-authored-by: Jean-François Roche <jfroche@affinitic.be>
Closes JENKINS-44681.
Picks up from #1248.
> Fix: Don't destroy credentials when re-creating organization folders

- docs/Home.md
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/ParameterizedRemoteTriggerContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
https://issues.jenkins.io/browse/JENKINS-68781
> Add missing options for Parameterized Remote Trigger Plugin

- build.gradle
- gradle.properties
To better manage dependencies of various libraries, we can use the
Parent POM for Jenkins Plugins, which we can import as a Platform, and
then manage our dependencies more appropriately.
We can use 3.57 as the closest plugin version that maps to our version
of Jenkins core.
As a step towards JENKINS-68275.
> Use the Jenkins plugin BOM

- job-dsl-plugin/build.gradle
As a step towards JENKINS-68275, and to generally keep up to date.
> Upgrade to the latest JPI plugin

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
This PR fixes an intermittant problem we've been seeing on our builds, where alternate builds fail because of `ConcurrentModificationException` in `ExecuteDslScripts`. This was raised as [JENKINS-69064](https://issues.jenkins.io/browse/JENKINS-69064).
**Explanation**
As part of the cleanup of removed templates in the `updateTemplates()` method, all seed job references are read for the removed template. These references are then filtered to those matching the seed job name. These matches are then removed from the seed job references.
However, the filtered references are a 'live' view (from `Collections2.filter`) based on the original seed job references, so attempting to remove them results in a `ConcurrentModificationException`.
**Fix**
The fix simply first converts the 'live' matches …
> Fix concurrent modification exception in ExecuteDslScripts

- .github/workflows/wiki.yml
Right now, it's a manual step I perform when I'm doing a release, which
leads to this being out-of-sync.
We can fortunately automate it following comments in [0] to do this more
easily.
[0]: https://github.com/orgs/community/discussions/25929
> Add a job to sync docs with GitHub Wiki

- .github/dependabot.yml
This should prevent noisy Dependabot PRs for a dependency we know cannot be upgraded without additional effort. If and when we decide to upgrade this dependency, the API viewer will need to be adapted and manual testing done to verify the API viewer displays correctly with the new version of Bootstrap.
> Disable Dependabot PRs for Bootstrap 4 and later

- .github/dependabot.yml
As in #1274, reduce Dependabot PR noise by disabling updates to Spock 2.x and later. Those versions require Groovy 2.5 or later, and Jenkins core is stuck on Groovy 2.4 due to JENKINS-53372.
> Disable Dependabot PRs for Spock 2.x and later

- .github/CODEOWNERS
- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- RELEASING.md
- docs/Home.md
- pom.xml
Align this plugin with other Jenkins plugins to allow for the release notes to be displayed on https://plugins.jenkins.io/job-dsl/releases/
> Enable Release Drafter

- .github/workflows/wiki.yml
- RELEASING.md
- build-wiki.sh
- job-dsl-plugin/pom.xml
- pom.xml
This had been temporarily ripped out in https://github.com/jenkinsci/job-dsl-plugin/pull/1265 to facilitate ease of development. The work has now been completed.
> Restore automated wiki updates

- .github/workflows/wiki.yml
- RELEASING.md
By automatically deploying the wiki on any push to `pom.xml`, we can take one step out of the release process.
> Simplify release process

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ExtendedEmailTriggersContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
While reviewing #1297 I noticed that we were lacking support for `BuildTrigger` and that it was trivial to add it.
> Add support for "Failure -> Unstable (Test Failures)" trigger

- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/BuildInDockerContext.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
This PR is for adding the ability to configure the network parameter of docker when running inside a container.
When configuring the "build inside docker" section of a job - under advanced options - you have the ability to configure manually the network and change it from "bridge" (the default) to "host"
in the job-dsl-plugin it was not exposed so I added it.
I added a new function "network" in docker context and exposed it in the wrapper.
Picture of the Maven clean install (after I added some tests for the new ability):
Picture of the actual use of the plugin after installing it on testing Jenkins:
https://issues.jenkins.io/browse/JENKINS-70542
-->
> Add ability to set network for Docker Custom Build Environment plugin

- .mvn/extensions.xml
- Jenkinsfile
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/MemoryJobManagementSpec.groovy
- job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ScriptRequestGeneratorSpec.groovy
- pom.xml
Without dropping support for Java 11, add support for running `mvn clean verify` on Java 17 and 21.
> Support building on Java 17 and 21

- job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/JenkinsJobManagement.java
The XStream default driver (based on XML Pull Parser 3rd edition) is one that core no longer prefers or uses for various reasons, including bugs parsing emoji in modern XML files. Instead core now uses the Streaming API for XML (StAX) that is built into modern versions of the Java Platform runtime environment. I have been working to slowly remove the old XPP3 parser from core, but I discovered that this plugin still had a hard-coded reference to it in one place and was broken when I removed the old driver from core. To avoid this problem I am instead having this plugin use core's default driver, which in newer versions is StAX.
I ran this plugin's tests against a core with XPP3 removed and observed they started failing. After this PR and …
> Use core default driver for XStream

- Jenkinsfile
- pom.xml
Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Testing done
===
Confirmed tests pass with Java 21 on Linux.
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull …
> Update pom parent, test with Jdk21.

- docs/JCasC.md
Add note on how relative file paths are handled.
As mentioned in jenkinsci/configuration-as-code-plugin#695 and jenkinsci/configuration-as-code-plugin#1145, it is not immediately obvious how relative paths are resolved. Adding a simple note may save a considerable time for someone new to this, like me.
> Improve JCasC docs

- job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/ExecuteDslScripts/config.jelly
Needed before https://github.com/jenkinsci/jenkins/pull/6867 can get merged.
`codemirror-config` attribute is expected to be a valid JSON except the start and end bracket as per https://github.com/jenkinsci/jenkins/blob/cd3b1517e7a553fd6fcf39e25c4bd1e18fbe39de/core/src/main/resources/lib/form/textarea.jelly#L70-L73.
In the upstream change `JSON#parse` is used instead of `eval` to transform the `codemirror-config` into a JSON object. `JSON#parse` cannot parse function attributes, hence the drop of `onBlur` handler in this PR. There seems to be no need for it because [this code](https://github.com/jenkinsci/jenkins/blob/83085bac0081f7366abf9c74616b1b1a9ad62bb3/core/src/main/resources/lib/form/textarea/textarea.js#L7-L12) re-adds it.
Tested interactively against …
> [JENKINS-71515] Make `codemirror-config` a valid JSON

- README.md
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/Folder/authorization.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/Job/authorization.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/JobAuthorizationContext/permission.groovy
- job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/JobAuthorizationContext/permissionAll.groovy
- job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/AuthorizationContext.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/FolderSpec.groovy
- job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
Make permissions matrix-auth-3.0+ compatible by adding support to explicitly assign permissions to groups or users.
With https://github.com/jenkinsci/matrix-auth-plugin/releases/tag/matrix-auth-3.0 ambiguous permissions will show a warning. With this change, matrix-auth-3.0+ users can resolve the warning by using the appropriate methods.
Closes #1249
See also https://issues.jenkins.io/browse/JENKINS-67411
Added test cases and manually deployed and tested the hpi on a Jenkins 2.440.3 instance.
> Make permissions matrix-auth-3.0+ compatible

- job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/EmbeddedApiDocGenerator.groovy
See [JENKINS-73759](https://issues.jenkins.io/browse/JENKINS-73759).
`LocalVariableTableParameterNameDiscoverer` was marked as deprecated in favour of `StandardReflectionParameterNameDiscoverer`. Since Spring Framework 6.1.0-M1, the class was removed from the framework. See https://github.com/spring-projects/spring-framework/commit/4d15b58ca421488d02f92e882c4a4b52c20328f6
Because of this, the plugin faces a bug in Jenkins 2.475+. 
As `StandardReflectionParameterNameDiscoverer` class is present in Spring Framework since version 4.0, this shouldn't be a problem to use the plugin with Jenkins prior or more recent than 2.475.
I just compiled the plugin
> [JENKINS-73759] Remove deprecated usage of Spring Framework class
