jenkinsci/job-dsl-plugin

job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/DescriptorImpl.java
Part of https://github.com/jenkinsci/job-dsl-plugin/pull/335.
=> Remove redundant implementation

Vagrantfile, config/codenarc/rules.groovy, docs/Home.md, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ScriptRequestGenerator.groovy, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/WorkspaceProtocol.groovy, job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/ExecuteDslScripts/help-additionalClasspath.html, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ScriptRequestGeneratorSpec.groovy, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/WorkspaceProtocolSpec.groovy
=> JAR and Ant-style pattern support for additional classpath option

docs/Grab-support.md, docs/Home.md, docs/Job-DSL-Commands.md, docs/Migration.md, docs/User-Power-Moves.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/AbstractJobManagement.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.java, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/GrabDeprecationTransformation.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/AbstractJobManagementSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/DslScriptLoaderSpec.groovy
See the mailing list for the discussion about removing `@Grab` support:
https://groups.google.com/forum/?fromgroups#!topic/job-dsl-plugin/EG6eqQYYI7M
=> Deprecated support for @Grab and @Grapes

docs/Home.md, docs/Job-DSL-Commands.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobType.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/CpsContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/WorkflowDefinitionContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobParentSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
New DSL methods:
```
def flow = '''node {
git url: 'https://github.com/jglick/simple-maven-project-with-tests.git'
def mvnHome = tool 'M3'
sh "${mvnHome}/bin/mvn -B verify"
}'''
job(type: Workflow) {
definition {
cps {
script(flow)
}
}
}
job(type: Workflow) {
definition {
cps {
script(readFileFromWorkspace('project-a-workflow.groovy'))
sandbox()
}
}
}
```
=> [JENKINS-26498] Support for Workflow Plugin

docs/Home.md
@daspilker: Thanks for the documentation - should I merge changes like this myself?
=> Fix typo in Release notes

docs/Home.md, docs/Job-DSL-Commands.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.java, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/ScmContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/SvnCheckoutStrategy.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/SvnContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
This is based on #71, but without support for repository browsers.
Resolves [JENKINS-17222](https://issues.jenkins-ci.org/browse/JENKINS-17222) and [JENKINS-17513](https://issues.jenkins-ci.org/browse/JENKINS-17513).
=> Advanced Subversion Settings

docs/Home.md, docs/Job-DSL-Commands.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/LabelParamContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContextSpec.groovy
Copied nodeparam for the style, I have docs and tests ready for this too.
Thanks,
=> labelparam support

docs/Home.md, docs/Job-DSL-Commands.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/CustomToolsContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
Add support for Custom Tools Plugin
* Tool names are mandatory
* Context to allow closures specifying optional params
* Tests added for both styles of calling
* Added release notes / documentation for this
=> Add support for Custom Tools plugin (JENKINS-26853)

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/EnvironmentVariableContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/EnvironmentVariableContributorsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
- overrideBuildParameters
- populateToolInstallations
=> improved support for EnvInject plugin

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
This seems to be a bad copy-paste.
=> Fix `notifySuspects` for the Jabber plugin

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/ScmContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/SvnContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/SvnLocationContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
=> Added credentials support for Subversion SCM

README.md, docs/Extending-the-DSL-from-your-Job-Scripts.md, docs/Home.md
* Make home page easier to read: it had started with 8 paragraphs containing 11 links (one section in bold) before the first heading, which seemed daunting.
* Make more of the links semantically meaningful.
* Some minor edits for tidiness / readability
=> Minor documentation updates

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/DebianContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy, job-dsl-plugin/build.gradle
Added support for the Debian package plugin
https://wiki.jenkins-ci.org/display/JENKINS/Debian+Package+Builder+Plugin
=> Added support for Debian Package plugin.

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Code, tests and docs.
I'll do other file types in a seperate PR.
=> Adding other options for plotBuildData

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
See https://issues.jenkins-ci.org/browse/JENKINS-27510
=> adding support for maven artifact uploader

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotSeriesContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotXMLContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Probably easier to do commit by commit.
There is one more file type to take care of (CSV) that I was hoping to do in a similar way to this if it looks acceptable.
=> Adding support for XML files to plotBuildData

docs/Folder-Reference.md, docs/Home.md, docs/Job-DSL-Commands.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Folder.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/AuthorizationContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/JobAuthorizationContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/FolderSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/JobAuthorizationContextSpec.groovy
I also deprecated camel case permission values and the permission method with two string arguments.
=> [JENKINS-27319] Added Folder Permissions

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
Probably also caused by [GROOVY-6263](http://jira.codehaus.org/browse/GROOVY-6263).
=> Fixed JENKINS-27767

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Implementation for Jenkins-27820
=> Add support for PowerShell build step in response to JENKINS-27820

docs/Home.md, docs/Job-reference.md, docs/Migration.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/CopyArtifactContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/CopyArtifactSelectorContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
* added new CopyArtifactContext
* deprecated support for the older versions of the Copy Artifact Plugin
* replaced and deprecated variants of copyArtifacts with more than two parameters
* added support for excludes filter (JENKINS-27838)
* refactoring
=> Copy Artifacts

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/CopyArtifactContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Add configuration of fingerprint Artifacts. A little bit convoluted as the config.xml syntax is inverted relative to the UI and the UI make more logical sense so the DSL follows the UI and not the XML.
=> Jenkins 27894

docs/View-Reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy
Adds "Robot Results" summary in List View
=> Added robotListView option for columns

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PullRequestPublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
This pull request is related to the New Feature describes on https://issues.jenkins-ci.org/browse/JENKINS-27932
=> JENKINS-27932: Pull Request Merge publisher support

Vagrantfile, docs/Home.md, docs/Job-reference.md, job-dsl-core/src/ast/groovy/javaposse/jobdsl/dsl/transform/CoreVersionASTTransformation.groovy, job-dsl-core/src/ast/resources/META-INF/services/org.codehaus.groovy.transform.ASTTransformation, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/MockJobManagement.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/RequiresCore.java, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/CoreVersionASTTransformationSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy, job-dsl-plugin/build.gradle, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
Added @RequiresCore annotation to require minimum core versions, set core dependency back to 1.554.2.
=> added @RequiresCore annotation

docs/Extending-the-DSL.md, docs/Home.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslExtensionMethod.java, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/MockJobManagement.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/AbstractExtensibleContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/ExtensibleContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContext.groovy, job-dsl-plugin/build.gradle, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ContextExtensionPoint.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java, job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/Messages.properties, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ContextExtensionPointSpec.groovy, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/TestContextExtensionPoint.java, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/TestContextExtensionPoint2.java, job-dsl-plugin/src/test/resources/config.xml, job-dsl-plugin/src/test/resources/config2.xml, job-dsl-plugin/src/test/resources/extension.xml
First step for the DSL extension point. Allows to add new methods with simple parameters and nested contexts.
=> [JENKINS-22151] DSL Extension Point

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublishBuildContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Add support for Build Publisher Plugin for Jenkins-28024
=> Add support for Publish Build plugin for JENKINS-28024.

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/HipchatPublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Adds support for HipChat Publisher [plugin](https://wiki.jenkins-ci.org/display/JENKINS/HipChat+Plugin).
=> Add support for HipChat Publisher

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/DslContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Added a way to configure the `lookupStrategy` in the `dsl` step
=> JENKINS-28171 Added `lookupStrategy` configuration

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/RundeckTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
Support for [RunDeck Plugin](https://wiki.jenkins-ci.org/display/JENKINS/RunDeck+Plugin)'s post-deployment job.
=> Add support for rundeck trigger

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/RobotFrameworkContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
I moved a couple more things than I should have because of my OC-ness.
=> Added support for `otherFiles` and `disableArchiveOutput` in RobotFramework Plugin

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/GitContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
[JENKINS-28264](https://issues.jenkins-ci.org/browse/JENKINS-28264)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/job-dsl-plugin/478)
=> [JENKINS-28264] Git SCM "Recursively update submodules" additional beh

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/ConditionalStepsContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
And I deprecated an undocumented variant of the runner method and the EvaluationRunners enum in ConditionalStepsContext.
=> [JENKINS-28308] generate non-single conditional build step to avoid XStream encoding issue

docs/Home.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
Also resolves [JENKINS-27492](https://issues.jenkins-ci.org/browse/JENKINS-27492).
=> removed anything that has been deprecated in 1.27

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/LogRotatorContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
Add a new method for logRotator that takes a closure.
=> add logRotator(Closure) method

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Added publisher to support build flow tests aggregation
=> [JENKINS-28851] New  Feature: Build Flow Test Aggregator plugin support

docs/The-Configure-Block.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/NodeEnhancement.groovy
=> [JENKINS-29022] explain behaviour of div operator when using attributes, fixed example

job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java, job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/Messages.properties, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
... when trying to move a job into a non-existing folder
=> [JENKINS-29100] provide better error message

docs/Home.md, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy, job-dsl-plugin/src/test/resources/order-a.xml, job-dsl-plugin/src/test/resources/order-b.xml
=> fixed a problem that caused a changing order of elements not to trigger a job update

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/PullRequestBuilderContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
=> Adding allowMembersOfWhitelistedOrgsAsAdmin as an option

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/JoinTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
=> added support for the Join Plugin

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/ConditionalStepsContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/MultiJobStepContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/MultiJobStepContextSpec.groovy
Tryout with generics. The IDE-Support doesn't work for me...
=> Multijob conditional step generics

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
The plugin name is "Fail The Build"; the build step name is "Set the build result".
=> Support 'Fail The Build' plugin

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/JobAuthorizationContext.groovy
=> Add blocksInheritance in AuthorizationContext

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobManagement.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobTemplateMissingException.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/BuildParametersContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/common/DownstreamTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
various minor fixes, see individual commits for details
=> code hygiene

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/RunConditionContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/condition/FilesMatchCondition.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/RunConditionContextSpec.groovy
Added the missing `filesmatch` condition from the Run Condition Plugin
=> [JENKINS-29503] added filesMatch to Run Condition plugin

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
Added support for the Heavy Job Plugin
=> [JENKINS-29499] added weight option for Heavy Job Plugin

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/DebianPackagePublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
added the missing publisher part of the Debian Package Builder Plugin (build step was already there)
=> [JENKINS-29502] added support debian package publisher

docs/Home.md, docs/IDE-Support.md, job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/idea.gdsl
See JENKINS-29668 and JENKINS-29669 for details.
=> removed IDEA GroovyDSL script, must be provided separately

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
https://wiki.jenkins-ci.org/display/JENKINS/Compress+Build+Log+Plugin
=> Add support for Compress Build Log plugin

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
added the missing `sandbox` option for Groovy Postbuild Plugin
=> [JENKINS-29500] added sandbox option to groovyPostbuild

docs/Home.md, docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/ClangScanBuildContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
added build step for the Clang Scan Build plugin. Publisher is still missing.
=> [JENKINS-29505] added support for Clang Scan-Build plugin

docs/Home.md, docs/Job-reference.md, docs/Migration.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/BuildPipelineContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/DownstreamContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/DownstreamTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/DownstreamTriggerParameterFactoryContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/PhaseJobContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/DownstreamTriggerParameterFactoryContextSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/MultiJobStepContextSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Replaces #561 which could not be merged after refactoring (#572).
=> [JENKINS-29801] Add support for BinaryFileParameterFactory

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/S3BucketPublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/S3EntryContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Add support for `useServerSideEncryption` and `flatten`.
=> Add more support for the S3 publisher

docs/Job-reference.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/PythonContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/VirtualenvContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Adds support for the https://wiki.jenkins-ci.org/display/JENKINS/ShiningPanda+Plugin plugin.
=> Add support for virtualenv steps

README.md, job-dsl-plugin/build.gradle
I updated the developers section to reflect the current state of affairs.
@quidryan, @andrewharmellaw, @sit, @sheehan are you OK with this?
=> removed authors from README, updated JPI developers section

job-dsl-api-viewer/src/js/App.js
Fixes the version select issue mentioned in https://github.com/jenkinsci/job-dsl-plugin/pull/479#issuecomment-139211146
=> reload detail pane when version select changes

job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java
The issue is that i thought that i really deletes jobs that i need to keep after swapping configuration from test seed job with real seed job. I thought that 'IGNORE' is not applied and spent many time changing parameters. Later realised that it just no accurate logging.
@daspilker i don't know this code base very well, please review
=> PoC Clarify summary of actions.

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/common/DownstreamTriggerParameterContext.groovy
This fixes occasional StackOverflow errors. See [Jenkins-30504](https://issues.jenkins-ci.org/browse/JENKINS-30504).
=> Explicitly set `delegate` on `predefinedProps`

job-dsl-api-viewer/README.md, job-dsl-api-viewer/src/css/main.less, job-dsl-api-viewer/src/js/views/ContextView.js
Minor API viewer updates:
* fix the margin under "Top-Level Methods"
* update build instructions in readme
=> fix root view margin. update readme.

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/remoteShell.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/RemoteShellContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Adds support for the [SSH plugin](https://wiki.jenkins-ci.org/display/JENKINS/SSH+plugin) to be able to execute shell commands on a remote site as a build step.
This is my first Java/Groovy contribution, so please bare with me if anything is wrong ;)
=> [JENKINS-30957] Add SSH plugin support

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
and deprecated support for older versions of HTML Publisher plugin
=> added workaround for JENKINS-31366

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/xshell.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/XShellContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Added support for [XShell](https://wiki.jenkins-ci.org/display/JENKINS/XShell+Plugin) plugin: 
- https://issues.jenkins-ci.org/browse/JENKINS-31512
=> [JENKINS-31512] Added support for XShell plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext/jobOwnership.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/properties/JobOwnershipContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/properties/PropertiesContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31531
Added support for [Ownership plugin](https://wiki.jenkins-ci.org/display/JENKINS/Ownership+Plugin)
=> [JENKINS-31531] Added Ownership plugin support

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/sloccount.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/SlocCountContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-29740
=> [JENKINS-29740] Added SlocCount plugin support

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/ruby.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31783
=> [JENKINS-31783] Added support for Ruby Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/bitbucketPush.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31788
=> [JENKINS-31788] Added support for Bitbucket Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/svnTag.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/SubversionTagContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31784
=> [JENKINS-31784] Added support for Subversion Tagging Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/cucumberReports.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/CucumberReportsContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
support for Cucumber Reports Plugin: https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin
https://issues.jenkins-ci.org/browse/JENKINS-31762
=> [JENKINS-31762] Added support for Cucumber Reports Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/cucumberTestResult.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/CucumberTestResultContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31815
=> [JENKINS-31815] Added support for Cucumber Test Result Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/mantis.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/MantisContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31911
=> [JENKINS-31911] Added support for Mantis plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/archiveGatling.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ArchiveGatlingContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
This pull request adds support for the gatling.io load test jenkins plugin
=> Adding gatling.io plugin support

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/dos.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/DosTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31879
=> [JENKINS-31879] Added support for DOS Trigger plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/flog.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/FlogContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
as part of the RubyMetrics Reports Plugin
https://wiki.jenkins-ci.org/display/JENKINS/RubyMetrics+plugin
=> [JENKINS-31830] Added support for flog publisher 

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/seleniumReport.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/SeleniumReportContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31887
Plugin: https://wiki.jenkins-ci.org/display/JENKINS/Seleniumhq+Plugin
=> [FIXED JENKINS-31887] Added support for Selenium Report plugin

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/seleniumHtml.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/SeleniumHtmlContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31886
=> [JENKINS-31886] Added support for Selenium Html Report plugin

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/nant.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/NAntContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31883
=> [FIXED JENKINS-31883] Added support for NAnt plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/railsStats.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/RailsStatsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
as part of the RubyMetrics Reports Plugin
https://issues.jenkins-ci.org/browse/JENKINS-31830
=> [JENKINS-31830] Added support for rails Stats publisher 

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/gitlabPush.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/GitlabTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-31789
=> [JENKINS-31789] Added GitLab Plugin support

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/rcov.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/RcovContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
as part of the RubyMetrics Reports Plugin
https://issues.jenkins-ci.org/browse/JENKINS-31830
=> [JENKINS-31830] Added support for rcov publisher

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/jslint.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/JSLintContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
Plugin: https://wiki.jenkins-ci.org/display/JENKINS/JSLint+plugin
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-32195
=> [JENKINS-32195] Added support for JSLint  plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/periodicFolder.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/PeriodicFolderTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-31719
CloudBees Folders Plugin Version 5.1
https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin
=> [JENKINS-31719] Add support for cloudbees-folder plugin computed triggers

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/cloverPHP.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/CloverPhpContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublishCloverHtmlReportContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-31557
[CloverPHP plugin](https://wiki.jenkins-ci.org/display/JENKINS/Clover+PHP+Plugin) support
=> [JENKINS-31557] Added support for CloverPHP plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/wsCleanup.groovy
This took some digging through code and trial and error to figure out how to use the failBuild option through DSL, so contributing an example to help others.
=> Add wsCleanup example for setting failBuild option

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/extendedEmail.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ExtendedEmailContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ExtendedEmailSendToContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ExtendedEmailTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ExtendedEmailTriggersContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
addresses JENKINS-28986, JENKINS-30542 and JENKINS-32131
=> improved support for Email-ext plugin

docs/Talks-and-Blog-Posts.md, docs/The-Configure-Block.md
- added configure block example for Confluence Publisher
- added blog entry for Job DSL
=> Added configure block example

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/Job/notifications.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/NotificationContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/NotificationEndpointContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
corresponding Jira : https://issues.jenkins-ci.org/browse/JENKINS-32882
=> [JENKINS-32882] add support loglines parameter , introduced in notification-1.8

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/mattermost.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/MattermostPublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Added support for Mattermost Plugin: https://issues.jenkins-ci.org/browse/JENKINS-32764
=> [JENKINS-32764] Added support for Mattermost Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/Job/lockableResources.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/LockableResourcesContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
This is extension to lockableResource , adding ability to specify resource label, and because of this also made resource names optional
=> [JENKINS-32906] Add support specifying LockableResources by Label

CONTRIBUTING.md
Codehaus has closed it's doors.
=> Replaced codehaus link with groovy-lang link

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/MavenJob.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/jobs/MavenJobSpec.groovy
o Added incrementalBuild into MavenJob.
=> [JENKINS-33359] Add maven incrementalBuild option

job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/DslEnvironmentImplSpec.groovy
=> [JENKINS-33466] removed TestAbstractExtensibleContext

job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-33482
=> [JENKINS-33482] enhance Git one-liner test

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/JobFiltersContext/mostRecent.groovy, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/JobFiltersContext/unclassified.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/JobFiltersContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/jobfilter/MostRecentJobsFilter.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/jobfilter/UnclassifiedJobsFilter.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
Related to https://issues.jenkins-ci.org/browse/JENKINS-33416
=> [JENKINS-33416] add support for mostRecent and Unclassified jobs filters

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/JobFiltersContext/all.groovy, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/JobFiltersContext/allRelease.groovy, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/JobFiltersContext/release.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/JobFiltersContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
Related to https://issues.jenkins-ci.org/browse/JENKINS-33416
=> [JENKINS-33416] add support for all, allRelease and release jobs filters

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/buildResult.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/DslScriptLoader.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/BuildResultTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
- https://wiki.jenkins-ci.org/display/JENKINS/BuildResultTrigger+Plugin
Fixes [JENKINS-33463](https://issues.jenkins-ci.org/browse/JENKINS-33463)
=> [JENKINS-33463] Support BuildResultTriggerPlugin

docs/Extending-the-DSL.md, docs/Home.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/EnvironmentVariableContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/toplevel/EnvironmentVariableContributorsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/toplevel/EnvironmentVariableContributorsContextSpec.groovy
@dcoraboeuf can you have a look?
=> [JENKINS-32742] allow EnvironmentVariableContributorsContext to be extended

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-33675
=> [JENKINS-33675] Release Button column support

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-33676
=> [JENKINS-33676] slaveOrLabel, userName and lastConfigurationModification columns

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-33677
=> [JENKINS-33677] buildParameters, workspace and disableProject columns support

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/ListViewSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-33674
Say me if the changes are correct or not, or if I must doing another solution.
=> [JENKINS-33674] Deprecated `build-node-column`, replace by `extra-columns`

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext/priority.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/Job.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/properties/PropertiesContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/properties/PropertiesContextSpec.groovy
support for older versions is deprecated
=> [JENKINS-29678] added support for newer version of the Priority Sorter plugin

docs/Extending-the-DSL.md
=> Keep the version of the dependency for

job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/ScmContextSpec.groovy
Is that a better code style in Groovy or would you keep the previous style?
=> Improved code.

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/SonarContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
https://issues.jenkins-ci.org/browse/JENKINS-33792
=> [JENKINS-33792] SonarQube : add jdk and mavenInstallationName support

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/cmake.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/CMakeBuildToolStepContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/CMakeContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
- Added support for [CMake plugin](https://wiki.jenkins-ci.org/display/JENKINS/CMake+Plugin)
- [JENKINS-33829](https://issues.jenkins-ci.org/browse/JENKINS-33829)
- Already tested out in a vanilla jenkins sandbox
=> [JENKINS-33829] Added support for CMake Plugin

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/exportRuntimeParameters.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
- [Job Exporter Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+Exporter+Plugin)
- [JENKINS-33882](https://issues.jenkins-ci.org/browse/JENKINS-33882)
=> [JENKINS-33882] Added support for Job Exporter Plugin

job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/jython.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
- Added support for [Jython Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Jython+Plugin)
- [JENKINS-33881](https://issues.jenkins-ci.org/browse/JENKINS-33881)
=> [JENKINS-33881] Added support for Jython Plugin

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/step/StepContext/phing.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/PhingContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/StepContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy
- [Phing plugin](https://wiki.jenkins-ci.org/display/JENKINS/Phing+Plugin)
- [JENKINS-33887](https://issues.jenkins-ci.org/browse/JENKINS-33887)
=> [JENKINS-33887] Added support for the Phing Plugin

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/properties/MavenPropertiesContext/mavenInfo.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/properties/MavenInfoContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/properties/MavenPropertiesContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/jobs/MavenJob.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/properties/MavenPropertiesContextSpec.groovy
Plugin Wiki: https://wiki.jenkins-ci.org/display/JENKINS/Maven+Info+Plugin#MavenInfoPlugin-AssignnamefromPOM
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-32196
=> [JENKINS-32196] Added support for the Maven Info Plugin

docs/Home.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/consoleParsing.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/LogParserContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
- Added support for [Log Parser Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Log+Parser+Plugin)
- [JENKINS-33795](https://issues.jenkins-ci.org/browse/JENKINS-33795)
- Already tested out in a vanilla jenkins sandbox
=> [JENKINS-33795] Added support for Log Parser Plugin

Vagrantfile, docs/Home.md, job-dsl-plugin/build.gradle, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy, job-dsl-plugin/src/test/resources/order-a.xml, job-dsl-plugin/src/test/resources/order-b.xml
see individual commits for details
=> Updated Jenkins core dependency, Gradle JPI plugin and Jenkins test harness

RELEASING.md, build.gradle, docs/Extending-the-DSL.md, docs/IDE-Support.md, docs/Testing-DSL-Scripts.md, gradle.properties, job-dsl-api-viewer/build.gradle, job-dsl-plugin/build.gradle
=> Several build improvements

Vagrantfile, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/ContextHelperSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/FileJobManagementSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/step/StepContextSpec.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/DslEnvironment.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/EmbeddedApiDocGenerator.groovy, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/ExecuteDslScripts.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/MonitorTemplateJobs.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedJobsBuildAction.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsAction.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsBuildAction.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedObjectsBuildRunAction.java, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/GeneratedViewsBuildAction.java
see individual commits for details
=> Address issues detected while trying to update to Jenkins 2.x

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/DeliveryPipelineView.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/DeliveryPipelineViewSpec.groovy
Added support for paging, which is available in DeliveryPipelinePlugin since version 0.9.10.
=> Paging support for Delivery Pipeline View

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/DeliveryPipelineView.groovy
- add showTestResults and useTheme
=> enhance DeliveryPipelineView

docs/Home.md, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java, job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/Messages.properties, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
see https://groups.google.com/d/msg/job-dsl-plugin/HDdaa0X5Pzs/8WLhkYAFBAAJ
=> improved error message when trying to change the type of a view

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/ColumnsContext.groovy
- add extra column for testResult
=> enhance ListView

docs/The-Configure-Block.md
Hello,
some people are better at repeating after others (like I am), especially when they are new to something. I was reading through this article a couple of times and couldn't really comprehend how to create xml for the plugin. After reading that link (where the author explicitly said this then that) it became clear as day for me. 
I'm not sure about licensing, if you are allowed to post this link or not, but if not, tell me, I will write something similar for you to explain same concept, because right now I find this article challenging to undestand (althou, when i understood basic concept, this article seems easy) while that article is great for newcomers. 
Thanks, feel free to reject.
Have a nice day.
=> proposing change

docs/The-Configure-Block.md
=> fixing broken link

docs/Home.md, job-dsl-api-viewer/src/assets/javascripts/Dsl.js, job-dsl-api-viewer/src/assets/javascripts/templates/detail.hbs, job-dsl-api-viewer/src/assets/javascripts/templates/pluginDetail.hbs, job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JobDslPlugin.groovy
=> [JENKINS-38456] fixed problem with embedded API viewer when a plugin is not available in the Update Center

job-dsl-api-viewer/build.gradle
=> make sure App.js is first in combined file

job-dsl-api-viewer/src/assets/javascripts/Dsl.js, job-dsl-api-viewer/src/assets/javascripts/Settings.js
=> use plugin ID as title if plugin info is missing

job-dsl-api-viewer/index.html, job-dsl-api-viewer/src/assets/javascripts/App.js, job-dsl-api-viewer/src/assets/javascripts/Settings.js, job-dsl-api-viewer/src/assets/stylesheets/main.less
[JENKINS-38803](https://issues.jenkins-ci.org/browse/JENKINS-38803)
=> [JENKINS-38803] moved filter button and added indicator

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/DeliveryPipelineView.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/DeliveryPipelineViewSpec.groovy
added support for new sorting option availible in delivery pipeline view.
=> add support for new sorting option in delivery pipeline plugin

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/step/SystemGroovyContext.groovy
Found while browsing the online documentation
=> Fixed typo in comments

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/GitHubBranchSourceContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContextsSpec.groovy
Adding settings for:
- Build origin branches.
- Build origin branches also filed as PRs.
- Build origin PRs (merged with base branch).
- Build origin PRs (unmerged head).
- Build fork PRs (merged with base branch).
- Build fork PRs (unmerged head).
=> Adding GitHub specific settings for PRs

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext/gitlabPush.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/GitLabTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/triggers/TriggerContextSpec.groovy
... and deprecated support for older versions
=> [JENKINS-41485] enhanced support for the GitLab Plugin

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/common/Threshold.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/JoinTriggerContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
And deprecated support for the older versions of the Join Plugin.
=> [JENKINS-43219] enhanced support for the Join Plugin

docs/Home.md, docs/Migration.md, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/StashNotifierContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Also deprecated support for the older versions of the Stash Notifier Plugin.
=> [JENKINS-42900] enhanced support for the Stash Notifier Plugin

job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/MavenPublisherContextSpec.groovy
This is a fix for the issue I described in https://groups.google.com/forum/#!topic/job-dsl-plugin/k2arf8cuEVU
Seems to be another instance of, except the update to Groovy 2.4 made it somehow worse. Let's hope this will finally be fixed in Groovy 2.5...
=> Fix static analysis publishers

Jenkinsfile, job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext/plotBuildData.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PlotContext.groovy, job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy, job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
adding support for yaxisminimum and yaxismaximum
=> publishers / plotBuildData / plot: added yAxisMinimum and yAxisMaximum

job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/GlobalJobDslSecurityConfiguration/config.groovy
Real diff: https://github.com/jenkinsci/job-dsl-plugin/pull/1172/files?w=1
---
This looks wrong:
>  ![Screen Shot](https://user-images.githubusercontent.com/1831569/56478911-98154d80-64b2-11e9-9706-55c70c3ea737.png)
New and improved: 
> ![Screen Shot](https://user-images.githubusercontent.com/1831569/56478912-99df1100-64b2-11e9-91b7-1c72f31582d8.png)
=> Add section for security configuration

job-dsl-plugin/build.gradle
https://mvnrepository.com/artifact/io.jenkins/configuration-as-code?repo=jenkins-releases
=> update jenkins configuration-as-code plugin from 1.13 to 1.15

job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
See https://github.com/jenkinsci/job-dsl-plugin/pull/1216 for details.
=> improved flaky tests

docs/The-Configure-Block.md
=> fixed a typo

README.md
Raising as a PR for visibility to folks!
=> Add note about looking for co-maintainers

job-dsl-plugin/pom.xml, job-dsl-plugin/src/test/resources/expected-dsl.json, pom.xml
=> Bump baseline to 2.387.1

job-dsl-plugin/pom.xml, job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
See https://github.com/jenkinsci/job-dsl-plugin/pull/1452#issuecomment-2311328087
@basil FYI
Validated with `mvn clean verify`
=> Bump io.jenkins.plugins:custom-folder-icon from 2.9 to 2.13

CONTRIBUTING.md
Without installing you will get an error about the availability of jar module for the plugin.
Built the plugin and realized the missing step.
=> docs: Make docs clearer on how to hpi:run
